import gfootball.env as football_env
import os
import gym
import wandb
import argparse

from wandb.integration.sb3 import WandbCallback
from stable_baselines3 import PPO
from stable_baselines3.common.logger import configure
from stable_baselines3.common.callbacks import CallbackList, BaseCallback
from datetime import datetime

import gfootball.env.players.agent as agent_module
from custom_agent import Player as CustomPlayer
from custom_reward import FootballShapedReward
from curriculum_learning import CurriculumCallback

parser = argparse.ArgumentParser(description='Visualiza um agente treinado.')

parser.add_argument('--stage', type=str, required=True, help='Nome do modelo a ser carregado')

args = parser.parse_args()


#Class to save the métrics generated by my model
class FootballMetricsCallback(BaseCallback):
    def __init__(self):
        super().__init__()
        self.ep_reward = 0.0
        self.ep_len = 0

    def _on_step(self):
        reward = self.locals["rewards"][0]
        done = self.locals["dones"][0]
        info = self.locals["infos"][0]

        self.ep_reward += reward
        self.ep_len += 1

        if done:
            goals = info.get("score", (0, 0))[0]  # ajuste se o campo for diferente
            self.logger.record("custom/episode_reward", self.ep_reward)
            self.logger.record("custom/episode_length", self.ep_len)
            self.logger.record("custom/goals_scored", goals)

            self.ep_reward = 0.0
            self.ep_len = 0

        return True



"""scenario_name = os.getenv("SCENARIO_NAME", "academy_empty_goal_close")
total_timesteps = int(os.getenv("TOTAL_STEPS", "100000"))"""

STAGES = {
    1: {
        "scenario": "academy_empty_goal_close",
        "timesteps": 1_000_000,
        "reward": "none",
        "adversary": "default"
    },
    2: {
        "scenario": "academy_empty_goal",
        "timesteps": 2_000_000,
        "reward": "light",
        "adversary": "default"
    },
    3: {
        "scenario": "academy_run_to_score",
        "timesteps": 3_000_000,
        "reward": "medium",
        "adversary": "default"
    },
    4: {
        "scenario": ["academy_3_vs_1", "academy_5_vs_3"],
        "timesteps": 5_000_000,
        "reward": "medium",
        "adversary": "default"
    },
    5: {
        "scenario": "5_vs_5",
        "timesteps": 10_000_000,
        "reward": "advanced",
        "adversary": "custom"
    }
}

STAGE = int(args.stage)

config = STAGES[STAGE]

scenario_name = config["scenario"]

total_timesteps = config["timesteps"]

print(f"--> Configuração Python: Cenário={scenario_name}")


run = wandb.init(
    project="RL_Fut_PPO",
    entity="guilhermefrazao-ufg", 
    name=f"train_{scenario_name}_{STAGE}-{datetime.now().strftime('%d - %H:%M')}",
    sync_tensorboard=True,  
    monitor_gym=True,    
    save_code=True,  
    config={
        "exp": 1,
        "algo": "PPO",
        "scenario": scenario_name,
        "total_steps": total_timesteps,
        "learning_rate": 0.0003,
        "n_steps": 2048,
        "gamma": 0.97,
        "step_penalty": 0.001,
        "goal_bonus": 0.5,
    }
)


wandb_callback = WandbCallback(
    model_save_path=f"./models/{run.id}",
    model_save_freq=10000,
    verbose=2
)


log_path = f"./logs_gfootball/{run.id}"
new_logger = configure(log_path, ["stdout", "tensorboard"])


env = football_env.create_environment(
    env_name=scenario_name, 
    stacked=True, 
    representation='simple115v2',
    render=False, 
    write_goal_dumps=False,
    write_full_episode_dumps=False,
    write_video=False
)


if config["reward"] == "none":
    pass
elif config["reward"] == "light":
    env = FootballShapedReward(env, step_penalty=1e-4)
elif config["reward"] == "medium":
    env = FootballShapedReward(env, step_penalty=1e-4, goal_bonus=0.5)
elif config["reward"] == "advanced":
    env = FootballShapedReward(env, step_penalty=5e-5, goal_bonus=1.0)

if config["adversary"] == "custom":
    agent_module.Player = CustomPlayer


prev_stage = STAGE - 1

load_path = f"./models/exp{prev_stage}_model.zip"


if STAGE > 1 and os.path.exists(load_path):
    print(f"🔁 Carregando pesos do estágio anterior: {load_path}")
    model = PPO.load(load_path, env=env, device="cpu")
else:    
    model = PPO(
        "MlpPolicy", 
        env, 
        verbose=1, 
        tensorboard_log="./logs_gfootball/",
        learning_rate=0.0003,
        n_steps=2048,
        gamma=0.99,
        gae_lambda=0.95,
        ent_coef=0.01,
        vf_coef=0.5,
        device="cpu", # MlpPolicy funciona melhor na CPU
    )




"""THRESHOLDS = [0.8, 0.6, 0.5, 0.4]

curriculum = CurriculumCallback(THRESHOLDS, Scenario_curriculum, env)"""

model.set_logger(new_logger)

callback = CallbackList([wandb_callback, FootballMetricsCallback()]) #, curriculum])

print(f"Iniciando treinamento no cenário: {scenario_name}...")

model.learn(
    total_timesteps=total_timesteps,
    callback=callback
)


model_path = f"./models/exp{STAGE}_model"
os.makedirs(os.path.dirname(model_path), exist_ok=True)

model.save(model_path)


wandb.finish()
env.close()


